name: CI 🚀

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
          if-no-files-found: ignore
